
    //临时添加的数据——dhl
    let mock={
        subjects:[{
              'imgUrl':'http://oss10.damaicn.cn/xingquanpet_com/20190128/1704031805.jpg',
              'title':'给他洗澡的那些事',
              'subjectId':354
          },{
              'imgUrl':'http://oss10.damaicn.cn/xingquanpet_com/20190128/1705108400.jpg',
              'title':'家有俩娃',
              'subjectId':353
          },{
              'imgUrl':'http://oss10.damaicn.cn/xingquanpet_com/20190128/1707265824.jpg',
              'title':'难言之隐',
              'subjectId':350
          }],
          postInfos:[
            {
                'id':1,
                'images':[{
                    'id':1,
                    'imgUrl':'http://oss10.damaicn.cn/xingquanpet_com/20190128/1704031805.jpg'
                }],
                'title':'夕阳无限好',
                'like':100,
                'comment':72,
                'follow':47,
                'forward':14,
                'liked':false,
                'heartType':'md-heart-empty'
            },
            {
                'id':2,
                'images':[{
                    'id':2,
                    'imgUrl':'http://oss10.damaicn.cn/xingquanpet_com/20190128/1705108400.jpg'
                }],
                'title':'沧海月明珠有泪',
                'like':100,
                'comment':72,
                'follow':47,
                'forward':14,
                'liked':false,
                'heartType':'md-heart-empty'
            },
            {
                'id':3,
                'images':[{
                    'id':3,
                    'imgUrl':'http://oss10.damaicn.cn/xingquanpet_com/20190128/1707265824.jpg'
                }],
                'title':'心有灵犀一点通',
                'like':100,
                'comment':72,
                'follow':47,
                'forward':14,
                'liked':false,
                'heartType':'md-heart-empty'
            },
            {
                'id':4,
                'images':[{
                    'id':4,
                    'imgUrl':'http://oss10.damaicn.cn/xingquanpet_com/20190128/1704031805.jpg'
                }],
                'title':'夕阳无限好',
                'like':100,
                'comment':72,
                'follow':47,
                'forward':14,
                'liked':true,
                'heartType':'md-heart'
            },
            {
                'id':5,
                'images':[{
                    'id':5,
                    'imgUrl':'http://oss10.damaicn.cn/xingquanpet_com/20190128/1707265824.jpg'
                }],
                'title':'此情可待成追忆',
                'like':9,
                'comment':72,
                'follow':47,
                'forward':14,
                'liked':true,
                'heartType':'md-heart'
            },
        ]
      };
      module.exports={
          mock
      }